openapi: 3.1.0
info:
  title: Example Service
  version: 0.1.0

servers:
  - url: http://localhost:8080
    description: 
      Local development server

paths:
  /hello:
    get:
      summary: Returns a greeting
      parameters:
        - in: query
          name: name
          schema:
            type: string
          required: false
          description: 
            An optional name to address the greeting to.
      responses:
        "200":
          description: A success response with a greeting
          content: 
            text/plain:
              schema:
                type: string
  /reverse:
    post:
      summary: Reverses a given string
      requestBody:
        description: Contains the string to reverse
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReverseInput'
      responses:
        "200":
          description: A success response with the reversed string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReverseOutput'
        "400":
          description: An error occurred
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BasicError'

components:
  schemas:
    ReverseInput:
      type: object
      required:
        - 'original'
      properties:
        original:
          type: string
    ReverseOutput:
      type: object
      required:
        - 'original'
        - 'reversed'
      properties:
        original:
          type: string
        reversed:
          type: string
    BasicError:
      type: object
      required:
        - operationID
        - reason
      properties:
        operationID:
          type: string
        reason:
          type: string
