openapi: 3.1.0
info:
  title: Example Service
  version: 0.1.0

servers:
  - url: http://localhost:8080
    description: 
      Local development server

paths:
  /hello:
    get:
      summary: Returns a greeting
      parameters:
        - in: query
          name: name
          schema:
            type: string
          required: false
          description: 
            An optional name to address the greeting to.
      responses:
        "200":
          description: A success response with a greeting
          content: 
            text/plain; charset=utf-8:
              schema:
                type: string
              